server:
    port: 8001
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/hotelbook?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
  #spring.datasource.driver-class-name=com.mysql.jdbc.Driver   mysql6以上用加cj，以下的不加cj
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database: mysql

  #Mybatis扫描路径
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #对应我们的实体类所在的包
  type-aliases-package: com.fafa.entity

#配置日志
logging:
  level:
    root: INFO
    org:
     springframework:
       web: DEBUG
     hibernate: ERROR
  # logging.path=D:\\demo1
  file: ./provider.log